### ISSUE TITLE
Validation/Test code leak?

### ISSUE THREAD

**Issue by rajasagashe** [TellinaTool/nl2bash#10]
If you look at index 521 or 587 in dev, the commands also occur in train? Shouldn't the filtering be happening on the tokenized command instead since it's different than the command in the .filtered file?

**Comment by todpole3** [comment]
@rajasagashe The following commands returns nothing which shows that there are no command overlap in train vs. dev and train vs. test in terms of string matching.

```
cd data/bash
comm -12 <(sort train.cm.filtered) <(sort dev.cm.filtered)
comm -12 <(sort train.cm.filtered) <(sort test.cm.filtered)
```

But this is a very rough check. Can you copy-paste the dev set commands you found to be in the train set?

**Comment by todpole3** [comment]
I'm closing this issue because it is inactive. Feel free to reopen it if you're experiencing any problems.
