### ISSUE TITLE
On errors during `make data` and how to fix them

### ISSUE THREAD

**Issue by grwlf** [TellinaTool/nl2bash#16]
Hi. Thanks for very interesting paper. I've run the current version of this repo and unfortunately faced some errors. I'd like to name it and suggest fixes.

### ~~Division by zero at `spell_check.py`~~

~~Probably that is because `nlp_tools/spellcheck/most_common.txt` file doesn't exists. Since there is an archived version of this file, I think it is OK to just unpack it manually or provide `system` call which does it automatically.~~

I just needed to call top-level `make` before doing `./scripts $ make data`

### Folder `../../experiments` doesn't exist.

Probably one should just create it with a dummy file. 

### ~~Module `encoder_decoder` doesn't exist~~

It was a PYTHONPATH issue on my side.

**Comment by grwlf** [comment]
It turns out that I missed top-level setup instructions. Most of errors are gone now, only missing `experiments` folder is still an issue.

**Comment by todpole3** [comment]
Thanks @grwlf 

I have changed the path in Makefile to the correct one.
