### ISSUE TITLE
make data

### ISSUE THREAD

**Issue by cjy-cc** [TellinaTool/nl2bash#25]
Hello sir, I have a problem and trouble you.

# Convert raw parallel corpus to features taken by the neural network
./bash-run.sh --process_data --dataset bash
make: execvp: ./bash-run.sh: 权限不够
Makefile:10: recipe for target 'data' failed
make: *** [data] Error 127

**Comment by todpole3** [comment]
Looks like you don't have enough permission to run `./bash-run.sh` on your machine.

Please try `chmod 755 bash-run.sh` and start over again.

**Comment by cjy-cc** [comment]
Thank you very much, the problem has been successfully solved under your guidance
