### ISSUE TITLE
Difference in reported metrics between README/paper

### ISSUE THREAD

**Issue by jjcmoon** [TellinaTool/nl2bash#29]
The reported results for the automatic metrics (BLEU/TM) differ between the paper and the README. Especially for CopyNet there is a fairly big discrepancy. Is this caused by an error in the results used for the paper or is there another explanation?

An additional question: in appendix C of the nl2bash paper it says that the automatic measures were evaluated on the dev set. Why not on the test set?

Lastly: on the tellina.rocks demo, is the best model used (ST CopyNet), or the actual tellina model?

**Comment by todpole3** [comment]
1. It should be difference between dev vs. test set. The results in README should be test set results.
2. We benchmark all models on the dev set and only evaluate the two best ones on the test set.
3. ST CopyNet is used on the tellina.rocks website.
