### ISSUE TITLE
question about command matching score

### ISSUE THREAD

**Issue by shuyanzhou** [TellinaTool/nl2bash#31]
Hi,

Could I know why the command matching score is measured in [this way](https://github.com/TellinaTool/nl2bash/blob/466c5fe873ab08c7cc0112ea1521cc6ad9c20992/eval/token_based.py#L34)?

It looks a bit less straightforward to me. 

I am trying something slightly different:
```python
def CMS2(ast1, ast2):
    # ast1 is gt, ast2 is prediction
    token_dict1 = get_content_tokens(ast1)
    token_dict2 = get_content_tokens(ast2)
    tokens = set([*token_dict1] + [*token_dict2])
    hit = 0
    for token in tokens:
        hit += min(token_dict1.get(token, 0), token_dict2.get(token, 0))
    p = hit / (sum(token_dict2.values()) + 1e-10)
    r = hit / (sum(token_dict1.values()) + 1e-10)
    f1 = 2 * p * r / (p + r + 1e-10)

    return p, r, f1
```

Do you think it makes sense?

Thanks!

**Comment by todpole3** [comment]
Hi @shuyanzhou,

The CMS score was implemented as a coarse measurement of "content token" overlap between the predicted command and the ground truth command. 

My original implementation converts both the predicted command and the ground truth command to "content token vectors" and compute the cosine similarity. Your implementation measures "hit rate". I don't have a strong opinion regarding which one makes more sense.

**Comment by shuyanzhou** [comment]
Thanks @todpole3, I did not realize it is cosine similarity. It makes more sense now.
