### ISSUE TITLE
Number of train/dev/test examples doesn't match

### ISSUE THREAD

**Issue by jiacheng-ye** [TellinaTool/nl2bash#36]
Hello,

I've run make data, but the number of resulting data is mismatched with the reported. I got: 
```
all.nl: 12607
all.nl.filtered: 11546
train.nl.filtered: 9985
dev.nl.filtered: 782
 test.nl.filtered: 779
```

**Comment by todpole3** [comment]
Thanks for catching this!

I rolled back to an earlier commit in 2018 (9aff4956d5c8450c1d7cc0481255bf0fe4d27050) and was able to generate data that matches the stats in the paper. I think one of the later changes alternated the filtering criteria. I will look into it. Meanwhile could you give the hacky solution a try (esp. if you just need the data).

**Comment by jiacheng-ye** [comment]
Solved, thanks~
