### ISSUE TITLE
Question about new command, bashlint not seem to support it?

### ISSUE THREAD

**Issue by yhfwww** [TellinaTool/nl2bash#37]
Hi, I have read the bashlint code carefully and there are some details that are not very clear. Where does the .txt files in the folder come from and does bashlint only support these commands for top 100? If I need to parse new commands, what do I need to do?

**Comment by todpole3** [comment]
You're right. The .txt grammar files were manually written by an author of NL2Bash. As a result, the bashlint toolkit only supports the top 100 commands -- I believe it can parse new commands to a pretty good AST, but the nuances would not be guaranteed. If there are new commands that need precise processing, you can manually construct their grammar and add to the .txt files.

**Comment by yhfwww** [comment]
@todpole3  Thank you for your answer.
I am just starting out in this field and would like to ask if there are any other tools to get an AST for bash commands or if there are other better tools in this area of study. Would you be able to give me a bit of information.

**Comment by todpole3** [comment]
Back when we were developing this project we found nothing else to be better. This https://explainshell.com/ website can parse more commands, and you can take a look at their opensource code https://github.com/idank/explainshell

Please reopen this issue if you have more questions.
