### ISSUE TITLE
bash-token.sh: Bad substitution

### ISSUE THREAD

**Issue by loveJasmine** [TellinaTool/nl2bash#8]
mldl@ub1604:~/ub16_prj/nl2bash/experiments$ 
mldl@ub1604:~/ub16_prj/nl2bash/experiments$ 
mldl@ub1604:~/ub16_prj/nl2bash/experiments$ make train
./bash-token.sh
./bash-token.sh: 5: ./bash-token.sh: Bad substitution
Makefile:41: recipe for target 'train' failed
make: *** [train] Error 2
mldl@ub1604:~/ub16_prj/nl2bash/experiments$ ll
total 44
drwxrwxr-x  2 mldl mldl 4096 9月  22 21:48 ./
drwxrwxr-x 11 mldl mldl 4096 9月  22 21:48 ../
-rwxrwxr-x  1 mldl mldl  590 9月  22 21:48 bash-char.sh*
-rwxrwxr-x  1 mldl mldl  632 9月  22 21:48 bash-copy-char.sh*
-rwxrwxr-x  1 mldl mldl  672 9月  22 21:48 bash-copy-partial-token.sh*
-rwxrwxr-x  1 mldl mldl  664 9月  22 21:48 bash-copy.sh*
-rwxrwxr-x  1 mldl mldl  630 9月  22 21:48 bash-partial-token.sh*
-rwxrwxr-x  1 mldl mldl  409 9月  22 21:48 bash-run.sh*
-rwxrwxr-x  1 mldl mldl  622 9月  22 21:48 bash-token.sh*
-rw-rw-r--  1 mldl mldl 1671 9月  22 21:48 Makefile
-rw-rw-r--  1 mldl mldl  929 9月  22 21:48 README.md
mldl@ub1604:~/ub16_prj/nl2bash/experiments$ vim bash-token.sh 
mldl@ub1604:~/ub16_prj/nl2bash/experiments$

**Comment by loveJasmine** [comment]
I just followed the instruction of readme
got the error when do 'make train'

**Comment by todpole3** [comment]
The problem is likely caused by the shebang I added to the experiment scripts.

I've updated them all to `#!/bin/bash`. Please see if that helps.

References:
https://stackoverflow.com/questions/20615217/bash-bad-substitution
https://askubuntu.com/questions/141928/what-is-difference-between-bin-sh-and-bin-bash
