### ISSUE TITLE
Provide online demo website

### ISSUE THREAD

**Issue by impredicative** [TellinaTool/nl2bash#9]
Can you provide a demo website where a user could type in natural language and get the command as output? As a motivational example, consider http://conceptnet.io which provides a demo search on their main page for their model. Thanks.

**Comment by todpole3** [comment]
This one: http://tellina.rocks

**Comment by impredicative** [comment]
Nice, but can the link be added to the readme?

**Comment by todpole3** [comment]
Okay, done!

**Comment by impredicative** [comment]
s/to interactive/to interact/

**Comment by todpole3** [comment]
Thanks!

**Comment by impredicative** [comment]
I request not publishing the city name of the web user in the usage history shown on the site. It can be used to identify people who wish to remain anonymous. Showing the state and country is IMO okay, however.

**Comment by todpole3** [comment]
Good point. We've changed it.
